#!/bin/bash

counter=1
while IFS= read -r svg_content; do
  if [[ -n "$svg_content" ]]; then
    echo "Processing SVG $counter..." >&2
    rsvg-convert -f png - <<< "$svg_content" > "tmp/output_$counter.png"
    ((counter++))
  fi
done